# schnet config file
train:
  epochs: 300
  accelerator: gpu
  number_of_checkpoints: 1
  devices: 1
  patience: 50
  run_name: test0
  experiment_name: cgcnn_basic
  version: '1.0'


data:
  additional_compound_features: is_metal_cgcnn # is_metal_cgcnn, magpie, lattice
  additional_atom_features: null # soap
  root_dir: data/cgcnn_data_mp_metal_nonmetal          #        #cgcnn_junwen_july_3_kdist
  model_name: schnet
  id_prop_csv: id_prop.csv
  checkpoint_path: trained_models/cgcnn/is_metal_nh2/is_metal.ckpt
  data_file: data/cgcnn_data_mp_metal_nonmetal/mp_metal_nonmetal_no_structural_duplicates.pkl
  features_file: embeddings/atom_init_original.json
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  lmdb_exist: true
  lmdb_test_name: test_data.lmdb
  lmdb_train_name: train_data.lmdb
  lmdb_val_name: val_data.lmdb
  batch_size: 32
  graph_params:
    radius: 10.0
    max_neighbors: 12
  pin_memory: false
  random_seed: 42
  stratify: false
  scale_y: false
  soap_params: null
  #   r_cut: 10.0
  #   n_max: 8
  #   l_max: 6
  #   sigma: 1.0

model:  #clarify the question of weight initialization in lightning and random_seed for that
  name: schnet
  robust_regression: false
  quantile_regression: false
  classification: true
  num_classes: 2
  pooling_type: 'mean_pool' # other possibilities : ..
  additional_compound_features: false
  add_feat_len: 146

loss:
  name: RobustL2Loss # RobustL2Loss, RobustL1Loss, QuantileLoss, CrossEntropyLoss, HuberLoss, L1Loss, MSELoss, StudentTLoss
  quantile: 0.9 # for quantile regression
  student_nu: 5 # parameter for StudentTLoss

optim:
  weight_decay: 0.0002  # 1e-5
  learning_rate: 0.005
  weights: false
  optimizer: adamw
  momentum: 0.9
  scheduler: onecycle
  swa: false
  swa_lr: 0.005
  swa_start: 50

prediction:
  predict_for_validation: true